server:
  port: ${iport:8085}
#  servlet:
#    context-path: /api
spring:
  application:
    name: ige-monitor
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dburl:localhost:3306}/${dbname:ige_config}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: ${dbuname:root}
    password: ${dbpwd:123}



# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.itheima.ige.monitor.pojo
  global-config:
    db-config:
      sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
      logic-delete-value: 2
      logic-not-delete-value: 1
#开启增强 - 作者/团队信息记录
knife4j:
  enable: true

#Netty配置
ige:
  rpc:
    port: ${rport:28888}
  data:
    maxlgt: 20*1024
logging:
  level:
    root: info

